import { ProductType } from '../../src/types';

export interface ProductTestConfig {
  productType: ProductType;
  productName: string;
  supportsMaturity: boolean;
  supportsCancellation: boolean;
  mandatoryBookingFields: Record<string, any>;
  amendmentFields: Record<string, any>;
}

export const PRODUCT_TEST_CONFIGS: Record<ProductType, ProductTestConfig> = {
  IRS: {
    productType: 'IRS',
    productName: 'Interest Rate Swap',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      counterpartyName: 'Global Bank Corp',
      counterpartyLei: 'CPTY-LEI-9999',
      notional: 10000000,
      currency: 'USD',
      fixedRate: 3.85,
      dayCount: '30/360',
      frequency: '6M',
      index: 'SOFR',
      indexTenor: '3M',
      spreadBps: 5,
    },
    amendmentFields: {
      notional: 15000000,
      fixedRate: 4.10,
      counterpartyName: 'Apex Capital Ltd',
      spreadBps: 10,
    },
  },
  CAP_FLOOR: {
    productType: 'CAP_FLOOR',
    productName: 'Interest Rate Cap / Floor',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      capFloorType: 'CAP',
      direction: 'BUY',
      strikeRate: 4.00,
      underlyingIndex: 'SOFR',
      indexTenor: '3M',
      currency: 'USD',
      notional: 5000000,
      premiumAmount: 25000,
      paymentFrequency: '6M',
      dayCount: '30/360',
    },
    amendmentFields: {
      strikeRate: 4.25,
      notional: 7500000,
      premiumAmount: 35000,
    },
  },
  SWAPTION: {
    productType: 'SWAPTION',
    productName: 'Swaption',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      swaptionType: 'PAYER',
      direction: 'BUY',
      strikeRate: 3.75,
      underlyingTenorYears: 5,
      settlementType: 'CASH',
      currency: 'USD',
      notional: 8000000,
      premiumAmount: 40000,
      underlyingFloatingIndex: 'SOFR',
    },
    amendmentFields: {
      strikeRate: 3.95,
      notional: 12000000,
      premiumAmount: 55000,
    },
  },
  FX_FORWARD: {
    productType: 'FX_FORWARD',
    productName: 'FX Forward',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      currencyPair: 'EUR/USD',
      direction: 'BUY_BASE',
      baseCurrency: 'EUR',
      counterCurrency: 'USD',
      baseAmount: 2000000,
      counterAmount: 2160000,
      forwardRate: 1.0800,
      spotRate: 1.0780,
    },
    amendmentFields: {
      baseAmount: 3000000,
      forwardRate: 1.0850,
      counterAmount: 3255000,
    },
  },
  FX_OPTION: {
    productType: 'FX_OPTION',
    productName: 'FX Option',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      optionType: 'CALL',
      direction: 'BUY',
      currencyPair: 'GBP/USD',
      callCurrency: 'GBP',
      putCurrency: 'USD',
      callAmount: 1000000,
      putAmount: 1280000,
      strikePrice: 1.2800,
      premiumAmount: 15000,
      premiumCurrency: 'USD',
    },
    amendmentFields: {
      callAmount: 1500000,
      strikePrice: 1.2950,
      premiumAmount: 22000,
    },
  },
  RANGE_ACCRUAL: {
    productType: 'RANGE_ACCRUAL',
    productName: 'Range Accrual',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      lowerBarrier: 3.00,
      upperBarrier: 5.00,
      referenceIndex: 'SOFR',
      accrualRate: 4.50,
      currency: 'USD',
      notional: 10000000,
    },
    amendmentFields: {
      lowerBarrier: 3.25,
      upperBarrier: 4.75,
      accrualRate: 4.75,
    },
  },
  SNOW_RANGE: {
    productType: 'SNOW_RANGE',
    productName: 'SnowRange Accrual',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      lowerBarrier: 2.80,
      upperBarrier: 5.20,
      referenceIndex: 'SOFR',
      accrualRate: 4.80,
      memoryRate: 1.20,
      currency: 'USD',
      notional: 10000000,
    },
    amendmentFields: {
      accrualRate: 5.00,
      memoryRate: 1.50,
    },
  },
  TARN: {
    productType: 'TARN',
    productName: 'TARN Swap',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      targetCap: 15.00,
      referenceIndex: 'SOFR',
      fixedRate: 4.20,
      currency: 'USD',
      notional: 10000000,
    },
    amendmentFields: {
      targetCap: 18.00,
      fixedRate: 4.50,
    },
  },
  SNOWBALL: {
    productType: 'SNOWBALL',
    productName: 'Snowball Ratchet',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      initialCoupon: 5.50,
      ratchetSpread: 0.50,
      underlyingIndex: 'SOFR',
      floorRate: 2.00,
      currency: 'USD',
      notional: 10000000,
    },
    amendmentFields: {
      initialCoupon: 6.00,
      ratchetSpread: 0.75,
    },
  },
  BOND: {
    productType: 'BOND',
    productName: 'Fixed Income Bond',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      bondType: 'SOVEREIGN',
      isin: 'US912828C478',
      issuer: 'US Treasury',
      couponRate: 4.25,
      couponFrequency: '6M',
      faceValue: 100,
      cleanPrice: 98.50,
      yieldToMaturity: 4.55,
      currency: 'USD',
      notional: 10000000,
      dayCount: '30/360',
    },
    amendmentFields: {
      cleanPrice: 99.10,
      yieldToMaturity: 4.40,
    },
  },
  FRA: {
    productType: 'FRA',
    productName: 'Forward Rate Agreement (FRA)',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      fraRate: 3.95,
      fixingIndex: 'SOFR',
      indexTenor: '3M',
      settlementType: 'CASH',
      currency: 'USD',
      notional: 10000000,
      dayCount: 'ACT/360',
    },
    amendmentFields: {
      fraRate: 4.10,
    },
  },
  DEPOSIT: {
    productType: 'DEPOSIT',
    productName: 'Term Deposit / Loan',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      direction: 'LEND',
      depositRate: 4.10,
      termDays: 90,
      compoundingFrequency: 'NONE',
      currency: 'USD',
      notional: 10000000,
      dayCount: 'ACT/360',
    },
    amendmentFields: {
      depositRate: 4.25,
    },
  },
  REPO: {
    productType: 'REPO',
    productName: 'Repurchase Agreement (Repo)',
    supportsMaturity: true,
    supportsCancellation: true,
    mandatoryBookingFields: {
      repoType: 'CLASSIC_REPO',
      collateralIsin: 'US912828C478',
      collateralDescription: 'US Treasury 10Y Note',
      repoRate: 3.75,
      haircutPct: 2.0,
      purchasePrice: 10000000,
      currency: 'USD',
      dayCount: 'ACT/360',
    },
    amendmentFields: {
      repoRate: 3.90,
      haircutPct: 2.5,
    },
  },
};
